version: '3.8'

services:
  web:
    build: .
    command: gunicorn steinpizza.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume: